# Generated by Django 5.x on 2026-07-24

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('SUPERADMIN', 'Superadmin (Web Admin)'), ('OPERATOR', 'Operator (Telegram Operator)'), ('DRIVER', 'Haydovchi'), ('PASSENGER', "Yo'lovchi")], default='DRIVER', max_length=20, verbose_name='Foydalanuvchi Roli')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram ID')),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefon Raqami')),
                ('operator_password', models.CharField(blank=True, help_text='Web admin tomonidan Telegram botga kirish uchun beriladigan parol', max_length=100, null=True, verbose_name='Operator Telegram Bot Paroli')),
                ('is_driver_active', models.BooleanField(default=True, verbose_name='Haydovchi Holati (Aktiv)')),
                ('is_telegram_authenticated', models.BooleanField(default=False, verbose_name="Botda Avtorizatsiyadan o'tgan")),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BotSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_group_id', models.BigIntegerField(blank=True, help_text="Masalan: -100123456789 (Bot guruhda admin bo'lishi kerak)", null=True, verbose_name='Kuzatiladigan Guruh Telegram ID')),
                ('auto_broadcast', models.BooleanField(default=False, help_text="Belgilansa, guruhga tushgan e'lon operator tasdig'isiz birdaniga barcha haydovchilarga yuboriladi", verbose_name='Avtomatik Haydovchilarga Yuborish')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bot Sozlamasi',
                'verbose_name_plural': 'Bot Sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(max_length=255, verbose_name="Yo'lovchi Ismi / Username")),
                ('passenger_telegram_id', models.BigIntegerField(blank=True, null=True, verbose_name="Yo'lovchi Telegram ID")),
                ('passenger_username', models.CharField(blank=True, max_length=255, null=True, verbose_name="Yo'lovchi Telegram Usernami")),
                ('passenger_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name="Yo'lovchi Telefon Raqami")),
                ('raw_text', models.TextField(verbose_name='Asl Xabar Matni (Guruhdan)')),
                ('formatted_text', models.TextField(verbose_name="Formatlangan E'lon Matni")),
                ('from_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Qayerdan')),
                ('to_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Qayerga')),
                ('departure_time', models.CharField(blank=True, max_length=255, null=True, verbose_name="Jo'nash Vaqti")),
                ('status', models.CharField(choices=[('NEW', 'Yangi (Kutilmoqda)'), ('BROADCASTED', 'Haydovchilarga Yuborildi'), ('CANCELLED', 'Bekor Qilindi')], default='NEW', max_length=20, verbose_name='Holati')),
                ('group_message_id', models.BigIntegerField(blank=True, null=True, verbose_name='Guruh Xabar ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan Vaqti')),
                ('created_by_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_announcements', to='main.user', verbose_name='Tasdiqlagan Operator')),
            ],
            options={
                'verbose_name': "E'lon / Buyurtma",
                'verbose_name_plural': "E'lonlar / Buyurtmalar",
                'ordering': ['-created_at'],
            },
        ),
    ]
