# Generated by Django 6.0.7 on 2026-07-24 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Qabul Qilingan Vaqt'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='accepted_by_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_orders', to=settings.AUTH_USER_MODEL, verbose_name='Qabul Qilgan Haydovchi'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='drivers_group_message_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Haydovchilar Guruhi Xabar ID'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='source_group_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Manba Guruh ID'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='source_group_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Manba Guruh Nomi'),
        ),
        migrations.AddField(
            model_name='botsetting',
            name='drivers_group_id',
            field=models.BigIntegerField(blank=True, help_text="E'lonlar shu guruhga shablon formatida yuboriladi. Masalan: -100123456789", null=True, verbose_name='Haydovchilar Guruhi Telegram ID'),
        ),
        migrations.AddField(
            model_name='botsetting',
            name='order_counter',
            field=models.BigIntegerField(default=0, help_text='Oxirgi buyurtma tartib raqami', verbose_name='Buyurtma Raqam Hisoblagichi'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='status',
            field=models.CharField(choices=[('NEW', 'Yangi (Kutilmoqda)'), ('BROADCASTED', 'Haydovchilarga Yuborildi'), ('ACCEPTED', 'Haydovchi Qabul Qildi'), ('CANCELLED', 'Bekor Qilindi')], default='NEW', max_length=20, verbose_name='Holati'),
        ),
    ]
