# Generated by Django 6.0.7 on 2026-07-26 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_announcement_accepted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsetting',
            name='min_order_length',
            field=models.PositiveIntegerField(default=10, help_text='Shundan qisqa xabarlar buyurtma deb hisoblanmaydi (aqlli filtr)', verbose_name='Minimal Xabar Uzunligi'),
        ),
        migrations.AddField(
            model_name='botsetting',
            name='smart_filter',
            field=models.BooleanField(default=True, help_text="Salomlashish, emoji va juda qisqa xabarlarni o'tkazib yuborish", verbose_name='Aqlli Filtr Yoqilgan'),
        ),
        migrations.AddField(
            model_name='botsetting',
            name='superadmin_bot_password',
            field=models.CharField(blank=True, help_text="Telegram botda /admin buyrug'i uchun parol", max_length=100, null=True, verbose_name='Superadmin Bot Paroli'),
        ),
        migrations.AlterField(
            model_name='botsetting',
            name='drivers_group_id',
            field=models.BigIntegerField(blank=True, help_text="Eskirgan — endi 'Telegram Guruhlar' bo'limidan foydalaning", null=True, verbose_name='[Eskirgan] Haydovchilar Guruhi Telegram ID'),
        ),
        migrations.AlterField(
            model_name='botsetting',
            name='target_group_id',
            field=models.BigIntegerField(blank=True, help_text="Eskirgan — endi 'Telegram Guruhlar' bo'limidan foydalaning", null=True, verbose_name='[Eskirgan] Kuzatiladigan Guruh Telegram ID'),
        ),
        migrations.CreateModel(
            name='TelegramGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(help_text='Masalan: -1001234567890', unique=True, verbose_name='Guruh Telegram ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Guruh Nomi')),
                ('group_type', models.CharField(choices=[('PASSENGER', "Yo'lovchilar Guruhi (manba)"), ('DRIVER', 'Haydovchilar Guruhi (tarqatish)')], max_length=20, verbose_name='Guruh Turi')),
                ('is_active', models.BooleanField(default=True, help_text="O'chirilsa bot bu guruhni butunlay e'tiborsiz qoldiradi", verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_groups', to=settings.AUTH_USER_MODEL, verbose_name="Kim qo'shgan")),
            ],
            options={
                'verbose_name': 'Telegram Guruh',
                'verbose_name_plural': 'Telegram Guruhlar',
                'ordering': ['group_type', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BroadcastMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(verbose_name='Chat ID')),
                ('message_id', models.BigIntegerField(verbose_name='Xabar ID')),
                ('is_group', models.BooleanField(default=True, verbose_name='Guruhga yuborilgan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to='main.announcement', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': 'Yuborilgan Xabar',
                'verbose_name_plural': 'Yuborilgan Xabarlar',
                'unique_together': {('announcement', 'chat_id', 'message_id')},
            },
        ),
    ]
